/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/rook/rook/pkg/apis/chubao.rook.io/v1alpha1"
	scheme "github.com/rook/rook/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ChubaoFSClustersGetter has a method to return a ChubaoFSClusterInterface.
// A group's client should implement this interface.
type ChubaoFSClustersGetter interface {
	ChubaoFSClusters(namespace string) ChubaoFSClusterInterface
}

// ChubaoFSClusterInterface has methods to work with ChubaoCluster resources.
type ChubaoFSClusterInterface interface {
	Create(*v1alpha1.ChubaoCluster) (*v1alpha1.ChubaoCluster, error)
	Update(*v1alpha1.ChubaoCluster) (*v1alpha1.ChubaoCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ChubaoCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.ChubaoClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoCluster, err error)
	ChubaoFSClusterExpansion
}

// chubaoFSClusters implements ChubaoFSClusterInterface
type chubaoFSClusters struct {
	client rest.Interface
	ns     string
}

// newChubaoFSClusters returns a ChubaoFSClusters
func newChubaoFSClusters(c *ChubaoV1alpha1Client, namespace string) *chubaoFSClusters {
	return &chubaoFSClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the chubaoFSCluster, and returns the corresponding chubaoFSCluster object, and an error if there is any.
func (c *chubaoFSClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.ChubaoCluster, err error) {
	result = &v1alpha1.ChubaoCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ChubaoFSClusters that match those selectors.
func (c *chubaoFSClusters) List(opts v1.ListOptions) (result *v1alpha1.ChubaoClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ChubaoClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested chubaoFSClusters.
func (c *chubaoFSClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a chubaoFSCluster and creates it.  Returns the server's representation of the chubaoFSCluster, and an error, if there is any.
func (c *chubaoFSClusters) Create(chubaoFSCluster *v1alpha1.ChubaoCluster) (result *v1alpha1.ChubaoCluster, err error) {
	result = &v1alpha1.ChubaoCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		Body(chubaoFSCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a chubaoFSCluster and updates it. Returns the server's representation of the chubaoFSCluster, and an error, if there is any.
func (c *chubaoFSClusters) Update(chubaoFSCluster *v1alpha1.ChubaoCluster) (result *v1alpha1.ChubaoCluster, err error) {
	result = &v1alpha1.ChubaoCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		Name(chubaoFSCluster.Name).
		Body(chubaoFSCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the chubaoFSCluster and deletes it. Returns an error if one occurs.
func (c *chubaoFSClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *chubaoFSClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chubaofsclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched chubaoFSCluster.
func (c *chubaoFSClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ChubaoCluster, err error) {
	result = &v1alpha1.ChubaoCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("chubaofsclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
