// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CFSVersionSpec) DeepCopyInto(out *CFSVersionSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CFSVersionSpec.
func (in *CFSVersionSpec) DeepCopy() *CFSVersionSpec {
	if in == nil {
		return nil
	}
	out := new(CFSVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChubaoFSCluster) DeepCopyInto(out *ChubaoFSCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChubaoFSCluster.
func (in *ChubaoFSCluster) DeepCopy() *ChubaoFSCluster {
	if in == nil {
		return nil
	}
	out := new(ChubaoFSCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChubaoFSCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChubaoFSClusterList) DeepCopyInto(out *ChubaoFSClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChubaoFSCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChubaoFSClusterList.
func (in *ChubaoFSClusterList) DeepCopy() *ChubaoFSClusterList {
	if in == nil {
		return nil
	}
	out := new(ChubaoFSClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChubaoFSClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChubaoFSSpec) DeepCopyInto(out *ChubaoFSSpec) {
	*out = *in
	out.CFSVersion = in.CFSVersion
	in.Master.DeepCopyInto(&out.Master)
	in.MetaNode.DeepCopyInto(&out.MetaNode)
	in.DataNode.DeepCopyInto(&out.DataNode)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChubaoFSSpec.
func (in *ChubaoFSSpec) DeepCopy() *ChubaoFSSpec {
	if in == nil {
		return nil
	}
	out := new(ChubaoFSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataNodeSpec) DeepCopyInto(out *DataNodeSpec) {
	*out = *in
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.Resource.DeepCopyInto(&out.Resource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataNodeSpec.
func (in *DataNodeSpec) DeepCopy() *DataNodeSpec {
	if in == nil {
		return nil
	}
	out := new(DataNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MasterSpec) DeepCopyInto(out *MasterSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.Resource.DeepCopyInto(&out.Resource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MasterSpec.
func (in *MasterSpec) DeepCopy() *MasterSpec {
	if in == nil {
		return nil
	}
	out := new(MasterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetaNodeSpec) DeepCopyInto(out *MetaNodeSpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	in.Resource.DeepCopyInto(&out.Resource)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaNodeSpec.
func (in *MetaNodeSpec) DeepCopy() *MetaNodeSpec {
	if in == nil {
		return nil
	}
	out := new(MetaNodeSpec)
	in.DeepCopyInto(out)
	return out
}
